version: '3.3'

services:
    filebrowser:
        image: filebrowser/filebrowser
        entrypoint:
            [
                '/filebrowser',
                '-a',
                '0.0.0.0',
                '-p',
                '80',
                '-d',
                '/database/filebrowser.db'
            ]
        restart: always
        volumes:
            - 'data:/srv'
            - 'db:/database'
            - 'config:/etc/filebrowser'
        networks:
            - home-station
        labels:
            home-station.app: '@github.com/home-station-org/apps:filebrowser'
            home-station.app-version: 0.1.0
            home-station.http.ui.port: 80
            home-station.http.ui.subdomain: "filebrowser"
            home-station.http.ui.title: "File Browser"

volumes:
  data:
  db:
  config:
            
networks:
  home-station:
    external: true
