version: '3.3'
services:
    filebrowser:
        image: filebrowser/filebrowser
        entrypoint:
            [
                '/filebrowser',
                '-a',
                '0.0.0.0',
                '-p',
                '80',
                '-d',
                '/database/filebrowser.db'
            ]
        restart: always
        volumes:
            - 'data:/srv'
            - '/var/lib/docker/volumes:/srv/volumes'
            - 'db:/database'
            - 'config:/etc/filebrowser'
        networks:
            - home-station
        labels:
            home-station.enable: true
            home-station.app: 15d3d6c0-da16-4715-991e-026981c559dc
            home-station.app-version: 0.1.0
            traefik.enable: true
            traefik.http.routers.15d3d6c0-da16-4715-991e-026981c559dc.entrypoints: websecure
            traefik.http.routers.15d3d6c0-da16-4715-991e-026981c559dc.rule: HostRegexp(`^filebrowser\.[a-z.]+$`)
            traefik.http.routers.15d3d6c0-da16-4715-991e-026981c559dc.service: 15d3d6c0-da16-4715-991e-026981c559dc
            #traefik.http.routers.15d3d6c0-da16-4715-991e-026981c559dc.middlewares: authelia@docker
            traefik.http.services.15d3d6c0-da16-4715-991e-026981c559dc.loadBalancer.server.port: 80

volumes:
  data:
  db:
  config:
            
networks:
  home-station:
    external: true
