version: '3.3'
services:
    filebrowser:
        image: filebrowser/filebrowser
        container_name: filebrowser
        entrypoint:
            [
                '/filebrowser',
                '-c',
                '/etc/filebrowser/.filebrowser.json',
                '-d',
                '/database/filebrowser.db'
            ]
        restart: always
        volumes:
            - 'data:/srv'
            - '/var/lib/docker/volumes:/srv/volumes'
            - 'db:/database'
            - 'config:/etc/filebrowser'
        networks:
            - home-station
        labels:
            home-station.enable: true
            home-station.app: 15d3d6c0-da16-4715-991e-026981c559dc
            home-station.app-version: 0.1.0

volumes:
    data:
    db:
    config:

networks:
  home-station:
    external: true
