version: '3.3'
services:
    filebrowser:
        image: filebrowser/filebrowser
        container_name: filebrowser
        entrypoint:
            [
                '/filebrowser',
                '-c',
                '/etc/filebrowser/.filebrowser.json',
                '-d',
                '/database/filebrowser.db'
            ]
        restart: always
        volumes:
            - 'data:/srv'
            - '/var/lib/docker/volumes:/srv/volumes'
            - 'db:/database'
            - 'config:/etc/filebrowser'

volumes:
    data:
    db:
    config:
